apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: one2n-project
  namespace: argocd
spec:
  description: Project for student-api and dependent services
  sourceRepos:
    - 'https://github.com/Vishalbhj03/one2n-sre-ex9'
    - 'https://github.com/Vishalbhj03/*'
  destinations:
    - namespace: student-api
      server: 'https://kubernetes.default.svc'
    - namespace: student-db
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
